version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: bot_metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase_password
      MB_DB_HOST: postgres_metabase
      JAVA_OPTS: "-Xmx2g"
    volumes:
      - metabase_data:/metabase.db
    depends_on:
      - postgres_metabase
    restart: unless-stopped
    networks:
      - bot_network

  postgres_metabase:
    image: postgres:15
    container_name: bot_postgres_metabase
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase_password
    volumes:
      - postgres_metabase_data:/var/lib/postgresql/data
    networks:
      - bot_network
    restart: unless-stopped

  # Опциональный nginx для доступа
  nginx:
    image: nginx:alpine
    container_name: bot_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - metabase
    networks:
      - bot_network
    restart: unless-stopped

volumes:
  metabase_data:
  postgres_metabase_data:

networks:
  bot_network:
    driver: bridge
