version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase_simple
    network_mode: host
    environment:
      MB_DB_TYPE: h2
      JAVA_OPTS: "-Xmx1g"
    volumes:
      - ./metabase_data:/metabase.db
    restart: unless-stopped
