site_name: BOT_AI_V3 Documentation
site_url: https://example.com/

docs_dir: docs_v3/

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

nav:
  - 'Главная': 'index.md'
  - 'Ядро системы': 'core.md'
  - 'Торговая логика': 'trading.md'
  - 'Машинное обучение': 'ml.md'
  - 'Веб-интерфейс': 'web.md'
  - 'База данных': 'database.md'
  - 'Биржи': 'exchanges.md'
  - 'Стратегии': 'strategies.md'