"""
Точная конфигурация признаков из обучающего файла BOT_AI_V2/ааа.py
Используется для продакшена в точном соответствии с обученной моделью.
"""

# КРИТИЧНО: Эти признаки должны создаваться В ТОЧНОМ ПОРЯДКЕ!
# Модель была обучена именно на этих признаках в этом порядке.

PRODUCTION_FEATURES = [
    "returns",
    "high_low_ratio",
    "close_open_ratio",
    "close_position",
    "volume_ratio",
    "turnover_ratio",
    "vwap",
    "close_vwap_ratio",
    "vwap_extreme_deviation",
    "rsi",
    "rsi_oversold",
    "rsi_overbought",
    "macd",
    "macd_signal",
    "macd_diff",
    "bb_high",
    "bb_low",
    "bb_middle",
    "bb_width",
    "bb_position",
    "bb_breakout_upper",
    "bb_breakout_lower",
    "bb_breakout_strength",
    "atr",
    "atr_pct",
    "stoch_k",
    "stoch_d",
    "adx",
    "adx_pos",
    "adx_neg",
    "psar",
    "psar_trend",
    "psar_distance",
    "psar_distance_normalized",
    "ichimoku_conversion",
    "ichimoku_base",
    "ichimoku_span_a",
    "ichimoku_span_b",
    "ichimoku_cloud_thickness",
    "price_vs_cloud",
    "keltner_upper",
    "keltner_middle",
    "keltner_lower",
    "keltner_position",
    "donchian_upper",
    "donchian_middle",
    "donchian_lower",
    "donchian_breakout",
    "vwma_20",
    "close_vwma_ratio",
    "mfi",
    "mfi_overbought",
    "mfi_oversold",
    "cci",
    "cci_overbought",
    "cci_oversold",
    "williams_r",
    "ultimate_oscillator",
    "accumulation_distribution",
    "obv",
    "obv_ema",
    "obv_trend",
    "cmf",
    "adxr",
    "aroon_up",
    "aroon_down",
    "aroon_oscillator",
    "pivot",
    "resistance1",
    "support1",
    "resistance2",
    "support2",
    "dist_to_resistance1",
    "dist_to_support1",
    "roc",
    "trix",
    "hl_spread",
    "hl_spread_ma",
    "price_direction",
    "directed_volume",
    "volume_imbalance",
    "dollar_volume",
    "price_impact",
    "price_impact_log",
    "toxicity",
    "amihud_illiquidity",
    "amihud_ma",
    "kyle_lambda",
    "volatility_volume_ratio",
    "realized_vol_1h",
    "realized_vol_daily",
    "realized_vol_annual",
    "realized_vol",
    "volume_volatility_ratio",
    "volume_zscore",
    "volume_spike",
    "volume_spike_magnitude",
    "volatility_squeeze",
    "volatility_squeeze_duration",
    "bearish_divergence_rsi",
    "bullish_divergence_rsi",
    "bearish_divergence_macd",
    "bullish_divergence_macd",
    "obv_normalized",
    "obv_divergence",
    "momentum_1h",
    "momentum_4h",
    "momentum_24h",
    "momentum_acceleration",
    "spring_pattern",
    "indicators_consensus_long",
    "indicators_count_long",
    "indicators_consensus_short",
    "indicators_count_short",
    "trend_1h",
    "trend_1h_strength",
    "trend_4h",
    "trend_4h_strength",
    "daily_high",
    "daily_low",
    "daily_range",
    "position_in_daily_range",
    "near_daily_high",
    "near_daily_low",
    "uptrend_structure",
    "downtrend_structure",
    "news_risk",
    "liquidity_score",
    "liquidity_rank",
    "signal_strength",
    "long_liquidation_price",
    "short_liquidation_price",
    "long_liquidation_distance_pct",
    "short_liquidation_distance_pct",
    "current_leverage",
    "long_liquidation_risk",
    "short_liquidation_risk",
    "optimal_leverage",
    "safe_leverage",
    "cascade_risk",
    "funding_proxy",
    "long_holding_cost_daily",
    "short_holding_cost_daily",
    "var_95",
    "recommended_position_size",
    "hour",
    "minute",
    "hour_sin",
    "hour_cos",
    "dayofweek",
    "is_weekend",
    "dow_sin",
    "dow_cos",
    "day",
    "month",
    "month_sin",
    "month_cos",
    "asian_session",
    "european_session",
    "american_session",
    "session_overlap",
    "hurst_exponent",
    "fractal_dimension",
    "efficiency_ratio",
    "trend_quality",
    "realized_vol_5m",
    "realized_vol_15m",
    "garch_vol",
    "vol_regime",
    "return_entropy",
    "btc_beta",
    "idio_vol",
    "returns_ac_1",
    "returns_ac_5",
    "returns_ac_10",
    "price_jump",
    "jump_intensity",
    "ofi_persistence",
    "vpin",
    "liquidity_adj_returns",
    "cvar_5pct",
    "relative_strength_btc",
    "rs_btc_ma",
    "btc_close",
    "btc_returns",
    "btc_correlation",
    "sector",
    "sector_returns",
    "relative_to_sector",
    "returns_rank",
    "is_momentum_leader",
    "long_tp1_time",
    "long_tp2_time",
    "long_tp3_time",
    "long_sl_time",
    "short_tp1_time",
    "short_tp2_time",
    "short_tp3_time",
    "short_sl_time",
    "long_expected_value",
    "short_expected_value",
    "long_optimal_entry_time",
    "long_optimal_entry_price",
    "long_optimal_entry_improvement",
    "short_optimal_entry_time",
    "short_optimal_entry_price",
    "short_optimal_entry_improvement",
    "returns_5",
    "returns_10",
    "returns_20",
    "sma_5",
    "sma_10",
    "sma_20",
    "close_sma_5_ratio",
    "close_sma_10_ratio",
    "close_sma_20_ratio",
    "local_high_20",
    "local_high_50",
    "local_high_100",
    "local_low_20",
    "local_low_50",
    "local_low_100",
    "distance_from_high_20",
    "distance_from_high_50",
    "distance_from_high_100",
    "distance_from_low_20",
    "distance_from_low_50",
    "distance_from_low_100",
    "position_in_range_20",
    "position_in_range_50",
    "position_in_range_100",
]

# Общее количество: 231 признаков

# Признаки по категориям:
# basic: 37 признаков
# technical: 62 признаков
# microstructure: 9 признаков
# volume: 7 признаков
# volatility: 10 признаков
# temporal: 17 признаков
# correlation: 6 признаков
# momentum: 4 признаков
# trend: 7 признаков
# risk: 13 признаков
# other: 59 признаков

BASIC_FEATURES = [
    "returns",
    "high_low_ratio",
    "close_open_ratio",
    "close_position",
    "volume_ratio",
    "turnover_ratio",
    "vwap",
    "close_vwap_ratio",
    "vwap_extreme_deviation",
    "bb_position",
    "keltner_position",
    "close_vwma_ratio",
    "hl_spread",
    "hl_spread_ma",
    "volatility_volume_ratio",
    "volume_volatility_ratio",
    "volatility_squeeze_duration",
    "momentum_acceleration",
    "position_in_daily_range",
    "recommended_position_size",
    "efficiency_ratio",
    "returns_ac_1",
    "returns_ac_5",
    "returns_ac_10",
    "liquidity_adj_returns",
    "btc_returns",
    "sector_returns",
    "returns_rank",
    "returns_5",
    "returns_10",
    "returns_20",
    "close_sma_5_ratio",
    "close_sma_10_ratio",
    "close_sma_20_ratio",
    "position_in_range_20",
    "position_in_range_50",
    "position_in_range_100",
]

TECHNICAL_FEATURES = [
    "rsi",
    "rsi_oversold",
    "rsi_overbought",
    "macd",
    "macd_signal",
    "macd_diff",
    "bb_high",
    "bb_low",
    "bb_middle",
    "bb_width",
    "bb_breakout_upper",
    "bb_breakout_lower",
    "bb_breakout_strength",
    "atr",
    "atr_pct",
    "stoch_k",
    "stoch_d",
    "adx",
    "adx_pos",
    "adx_neg",
    "psar",
    "psar_trend",
    "psar_distance",
    "psar_distance_normalized",
    "ichimoku_conversion",
    "ichimoku_base",
    "ichimoku_span_a",
    "ichimoku_span_b",
    "ichimoku_cloud_thickness",
    "keltner_upper",
    "keltner_middle",
    "keltner_lower",
    "donchian_upper",
    "donchian_middle",
    "donchian_lower",
    "donchian_breakout",
    "mfi",
    "mfi_overbought",
    "mfi_oversold",
    "cci",
    "cci_overbought",
    "cci_oversold",
    "williams_r",
    "obv",
    "obv_ema",
    "obv_trend",
    "adxr",
    "aroon_up",
    "aroon_down",
    "aroon_oscillator",
    "roc",
    "trix",
    "bearish_divergence_rsi",
    "bullish_divergence_rsi",
    "bearish_divergence_macd",
    "bullish_divergence_macd",
    "obv_normalized",
    "obv_divergence",
    "ofi_persistence",
    "sma_5",
    "sma_10",
    "sma_20",
]

MICROSTRUCTURE_FEATURES = [
    "volume_imbalance",
    "price_impact",
    "price_impact_log",
    "toxicity",
    "amihud_illiquidity",
    "amihud_ma",
    "kyle_lambda",
    "liquidity_score",
    "liquidity_rank",
]

VOLUME_FEATURES = [
    "accumulation_distribution",
    "cmf",
    "directed_volume",
    "dollar_volume",
    "volume_zscore",
    "volume_spike",
    "volume_spike_magnitude",
]

VOLATILITY_FEATURES = [
    "realized_vol_1h",
    "realized_vol_daily",
    "realized_vol_annual",
    "realized_vol",
    "volatility_squeeze",
    "realized_vol_5m",
    "realized_vol_15m",
    "garch_vol",
    "vol_regime",
    "idio_vol",
]

TEMPORAL_FEATURES = [
    "long_holding_cost_daily",
    "short_holding_cost_daily",
    "hour",
    "hour_sin",
    "hour_cos",
    "dayofweek",
    "is_weekend",
    "dow_sin",
    "dow_cos",
    "day",
    "month",
    "month_sin",
    "month_cos",
    "asian_session",
    "european_session",
    "american_session",
    "session_overlap",
]

CORRELATION_FEATURES = [
    "btc_beta",
    "relative_strength_btc",
    "rs_btc_ma",
    "btc_close",
    "btc_correlation",
    "relative_to_sector",
]

MOMENTUM_FEATURES = [
    "momentum_1h",
    "momentum_4h",
    "momentum_24h",
    "is_momentum_leader",
]

TREND_FEATURES = [
    "trend_1h",
    "trend_1h_strength",
    "trend_4h",
    "trend_4h_strength",
    "uptrend_structure",
    "downtrend_structure",
    "trend_quality",
]

RISK_FEATURES = [
    "news_risk",
    "long_liquidation_price",
    "short_liquidation_price",
    "long_liquidation_distance_pct",
    "short_liquidation_distance_pct",
    "current_leverage",
    "long_liquidation_risk",
    "short_liquidation_risk",
    "optimal_leverage",
    "safe_leverage",
    "cascade_risk",
    "var_95",
    "cvar_5pct",
]

OTHER_FEATURES = [
    "price_vs_cloud",
    "vwma_20",
    "ultimate_oscillator",
    "pivot",
    "resistance1",
    "support1",
    "resistance2",
    "support2",
    "dist_to_resistance1",
    "dist_to_support1",
    "price_direction",
    "spring_pattern",
    "indicators_consensus_long",
    "indicators_count_long",
    "indicators_consensus_short",
    "indicators_count_short",
    "daily_high",
    "daily_low",
    "daily_range",
    "near_daily_high",
    "near_daily_low",
    "signal_strength",
    "funding_proxy",
    "minute",
    "hurst_exponent",
    "fractal_dimension",
    "return_entropy",
    "price_jump",
    "jump_intensity",
    "vpin",
    "sector",
    "long_tp1_time",
    "long_tp2_time",
    "long_tp3_time",
    "long_sl_time",
    "short_tp1_time",
    "short_tp2_time",
    "short_tp3_time",
    "short_sl_time",
    "long_expected_value",
    "short_expected_value",
    "long_optimal_entry_time",
    "long_optimal_entry_price",
    "long_optimal_entry_improvement",
    "short_optimal_entry_time",
    "short_optimal_entry_price",
    "short_optimal_entry_improvement",
    "local_high_20",
    "local_high_50",
    "local_high_100",
    "local_low_20",
    "local_low_50",
    "local_low_100",
    "distance_from_high_20",
    "distance_from_high_50",
    "distance_from_high_100",
    "distance_from_low_20",
    "distance_from_low_50",
    "distance_from_low_100",
]

# КРИТИЧЕСКИЕ ФОРМУЛЫ (должны быть точно такими же как в обучении):
CRITICAL_FORMULAS = {
    "macd": "macd / close * 100",  # Нормализованный MACD
    "macd_signal": "macd_signal / close * 100",
    "macd_diff": "macd_diff / close * 100",
    "btc_correlation": "window=96, min_periods=50",
    "returns": "np.log(close / close.shift(1))",  # LOG возвраты
    "amihud_illiquidity": "abs(returns) * 1e6 / turnover",  # * 1e6
    "price_impact": "abs(returns) * 100 / log10(dollar_volume + 100)",
    "volume_cumsum_log": "log1p transformation",
    "realized_vol_1h": "rolling(240).std() * sqrt(240)",  # 1h = 240 periods
}

INFERENCE_CONFIG = {
    "expected_features": 240,  # ИСПРАВЛЕНО: модель обучена на 240 признаках + enhanced features
    "feature_order_critical": True,
    "normalize_features": True,
    "handle_missing": "forward_fill",
    "min_history_required": 240,  # Для расчета всех индикаторов
}
