name: MLSignalStrategy
version: 1.0.0
description: "ML \u0441\u0442\u0440\u0430\u0442\u0435\u0433\u0438\u044F \u043D\u0430\
  \ \u043E\u0441\u043D\u043E\u0432\u0435 \u0441\u0438\u0433\u043D\u0430\u043B\u043E\
  \u0432 \u043E\u0442 UnifiedPatchTST \u043C\u043E\u0434\u0435\u043B\u0438"
enabled: true
min_confidence: 0.45
min_signal_strength: 0.3
signal_timeout_minutes: 10
position_size_percent: 0.02
max_positions: 1
use_ml_stop_loss: true
use_ml_take_profit: true
default_stop_loss_pct: 0.025
default_take_profit_pct: 0.05
trade_filters:
  allow_trading_hours: true
  trading_hours:
    start: 00:00
    end: '23:59'
  volatility_filter: true
  min_volatility: 0.001
  max_volatility: 0.1
  volume_filter: true
  min_volume_24h: 1000000
execution:
  order_type: limit
  time_in_force: GTC
  limit_price_offset: 0.0001
  max_slippage: 0.003
logging:
  log_signals: true
  log_trades: true
  log_performance: true
adaptive:
  enabled: true
  volatility_adjustment: true
  time_of_day_adjustment: true
  trend_adjustment: true
market_conditions:
  trending:
    position_size_multiplier: 1.2
    min_confidence: 0.4
  ranging:
    position_size_multiplier: 0.8
    min_confidence: 0.55
  high_volatility:
    position_size_multiplier: 0.6
    min_confidence: 0.6
    default_stop_loss_pct: 0.04
symbol_overrides:
  BTCUSDT:
    position_size_percent: 0.03
    min_confidence: 0.4
  ETHUSDT:
    position_size_percent: 0.025
    min_confidence: 0.45
  DOGEUSDT:
    position_size_percent: 0.01
    min_confidence: 0.6
    default_stop_loss_pct: 0.05
order_type: MARKET
