created_at: '2025-07-28'
description: UnifiedPatchTST model for crypto trading
features:
  indicators:
    adx_period: 14
    atr_period: 14
    bb_period: 20
    bb_std: 2.0
    cci_period: 20
    macd_fast: 12
    macd_signal: 9
    macd_slow: 26
    rsi_period: 14
    stoch_period: 14
  microstructure:
    order_flow_periods:
    - 5
    - 10
    - 20
    volume_profile_bins: 10
  periods:
    long:
    - 60
    - 90
    - 120
    medium:
    - 20
    - 30
    - 45
    short:
    - 5
    - 10
    - 15
  temporal:
    include_day_of_week: true
    include_hour: true
    include_month: true
    include_quarter: true
  volatility:
    min_period: 20
    periods:
    - 10
    - 20
    - 30
    - 60
loss:
  auto_adjust_on_collapse: true
  class_weights:
  - 1.3
  - 1.3
  - 0.7
  collapse_threshold: 0.75
  entropy_min_weight: 0.2
  focal_alpha: 0.25
  focal_gamma: 2.0
  large_move_threshold: 0.003
  large_move_weight: 5.0
  min_entropy: 0.6
  task_weights:
    directions: 3.0
    future_returns: 1.0
    long_levels: 1.0
    risk_metrics: 0.5
    short_levels: 1.0
  use_dynamic_class_weights: true
  wrong_direction_penalty: 3.0
metrics:
  f1_score: 0.414
  training_samples: 1000000
  win_rate: 0.466
model:
  activation: gelu
  context_window: 96
  d_ff: 512
  d_model: 256
  direction_confidence_threshold: 0.5
  direction_l2_weight: 0.001
  dropout: 0.1
  e_layers: 3
  entropy_weight: 0.1
  input_size: 240
  l2_regularization: 0.001
  label_smoothing: 0.2
  min_entropy_threshold: 0.5
  n_heads: 4
  output_size: 20
  patch_len: 16
  stride: 8
  temperature: 2.0
  temperature_scaling: true
  type: UnifiedPatchTSTForTrading
output_names:
- future_return_15m
- future_return_1h
- future_return_4h
- future_return_12h
- direction_15m
- direction_1h
- direction_4h
- direction_12h
- long_will_reach_1pct_4h
- long_will_reach_2pct_4h
- long_will_reach_3pct_12h
- long_will_reach_5pct_12h
- short_will_reach_1pct_4h
- short_will_reach_2pct_4h
- short_will_reach_3pct_12h
- short_will_reach_5pct_12h
- max_drawdown_1h
- max_rally_1h
- max_drawdown_4h
- max_rally_4h
version: '4.0'
