# BOT_Trading v3.0 - Конфигурация логирования
# Настройки системы логирования для мульти-трейдер системы

version: 1
disable_existing_loggers: false

# Форматтеры логов
formatters:
  simple:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

  detailed:
    format: '%(asctime)s [%(levelname)s] %(name)s [%(filename)s:%(lineno)d] %(funcName)s(): %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

  json:
    format: '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "module": "%(module)s", "function": "%(funcName)s", "line": %(lineno)d, "message": "%(message)s"}'
    datefmt: '%Y-%m-%d %H:%M:%S'

  trader_format:
    format: '%(asctime)s [%(levelname)s] [TRADER:%(trader_id)s] %(name)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

# Обработчики логов
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: detailed
    stream: ext://sys.stdout

  main_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: /mnt/SSD/PYCHARMPRODJECT/BOT_AI_V3/data/logs/system.log
    maxBytes: 104857600  # 100MB
    backupCount: 10
    encoding: utf8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: /mnt/SSD/PYCHARMPRODJECT/BOT_AI_V3/data/logs/errors.log
    maxBytes: 52428800  # 50MB
    backupCount: 5
    encoding: utf8

  trades_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: /mnt/SSD/PYCHARMPRODJECT/BOT_AI_V3/data/logs/trades.log
    maxBytes: 104857600  # 100MB
    backupCount: 20
    encoding: utf8

  performance_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: /mnt/SSD/PYCHARMPRODJECT/BOT_AI_V3/data/logs/performance.log
    maxBytes: 52428800  # 50MB
    backupCount: 10
    encoding: utf8

  debug_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: /mnt/SSD/PYCHARMPRODJECT/BOT_AI_V3/data/logs/debug.log
    maxBytes: 52428800  # 50MB
    backupCount: 3
    encoding: utf8

# Конфигурация логгеров
loggers:
  # Основной логгер системы
  main:
    level: INFO
    handlers: [console, main_file, error_file]
    propagate: false

  # Логгер для трейдеров
  trader:
    level: INFO
    handlers: [console, main_file, trades_file]
    propagate: false

  # Логгер для торговых операций
  trading:
    level: INFO
    handlers: [trades_file, error_file]
    propagate: false

  # Логгер для бирж
  exchange:
    level: INFO
    handlers: [main_file, error_file]
    propagate: false

  # Логгер для стратегий
  strategy:
    level: INFO
    handlers: [main_file, trades_file]
    propagate: false

  # Логгер для ML моделей
  ml:
    level: INFO
    handlers: [main_file, performance_file]
    propagate: false

  # Логгер для базы данных
  database:
    level: INFO
    handlers: [main_file, error_file]
    propagate: false

  # Логгер для мониторинга
  monitoring:
    level: INFO
    handlers: [main_file, performance_file]
    propagate: false

  # Логгер для API
  api:
    level: INFO
    handlers: [main_file, error_file]
    propagate: false

  # Логгер для WebSocket
  websocket:
    level: INFO
    handlers: [main_file, error_file]
    propagate: false

  # Отладочный логгер
  debug:
    level: DEBUG
    handlers: [debug_file]
    propagate: false

  # Логгер для производительности
  performance:
    level: INFO
    handlers: [performance_file]
    propagate: false

  # Логгер для аудита
  audit:
    level: INFO
    handlers: [main_file, trades_file]
    propagate: false

# Внешние библиотеки
  asyncio:
    level: WARNING
    handlers: [error_file]
    propagate: false

  sqlalchemy:
    level: WARNING
    handlers: [error_file]
    propagate: false

  urllib3:
    level: WARNING
    handlers: [error_file]
    propagate: false

  requests:
    level: WARNING
    handlers: [error_file]
    propagate: false

  websockets:
    level: WARNING
    handlers: [error_file]
    propagate: false

# Корневой логгер
root:
  level: INFO
  handlers: [console, main_file, error_file]
