# BOT_Trading v3.0 - Системная конфигурация
# Основные настройки мульти-трейдер системы

system:
  name: "BOT_Trading_v3"
  version: "3.0.0"
  environment: "development"  # development, staging, production
  
  # Системные ограничения
  limits:
    max_traders: 10
    max_concurrent_trades: 50
    max_memory_usage_mb: 2048
    max_cpu_usage_percent: 80
  
  # Настройки производительности
  performance:
    worker_threads: 4
    async_pool_size: 100
    connection_pool_size: 20
    cache_size_mb: 512

# Конфигурация базы данных
database:
  type: "postgresql"
  host: "127.0.0.1"
  port: 5432
  name: "bot_trading_v3"
  user: "postgres"
  password: "${DB_PASSWORD}"
  
  # Настройки пула подключений
  pool:
    min_connections: 5
    max_connections: 25
    connection_timeout: 30
    idle_timeout: 300
    
  # Настройки миграций
  migrations:
    auto_migrate: true
    backup_before_migration: true

# Мониторинг и здоровье системы
monitoring:
  enabled: true
  health_check_interval: 30  # секунды
  metrics_collection_interval: 10  # секунды
  
  # Prometheus метрики
  prometheus:
    enabled: true
    port: 9090
    path: "/metrics"
  
  # Алерты
  alerts:
    enabled: true
    telegram_enabled: false
    email_enabled: false
    
    # Пороги для алертов
    thresholds:
      memory_usage_percent: 85
      cpu_usage_percent: 90
      error_rate_percent: 5
      latency_ms: 1000

# Настройки логирования
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "structured"  # simple, structured, json
  
  # Файлы логов
  files:
    main: "logs/system.log"
    trades: "logs/trades.log"
    errors: "logs/errors.log"
    
  # Ротация логов
  rotation:
    max_size_mb: 100
    backup_count: 10
    
  # Внешние системы
  external:
    sentry:
      enabled: false
      dsn: "${SENTRY_DSN}"

# Настройки безопасности
security:
  # Шифрование API ключей
  encryption:
    enabled: true
    key_rotation_days: 30
    
  # Ограничения доступа
  access:
    max_login_attempts: 5
    lockout_duration_minutes: 30
    
  # Аудит
  audit:
    enabled: true
    log_all_actions: true
    retention_days: 90

# Настройки API
api:
  rest:
    enabled: true
    host: "0.0.0.0"
    port: 8080
    cors_enabled: true
    rate_limiting:
      enabled: true
      requests_per_minute: 100
      
  websocket:
    enabled: true
    port: 8081
    max_connections: 100
    heartbeat_interval: 30
    
  webhook:
    enabled: true
    port: 8082
    timeout_seconds: 30
    retry_attempts: 3

# Настройки уведомлений
notifications:
  telegram:
    enabled: false
    bot_token: "${TELEGRAM_BOT_TOKEN}"
    chat_id: "${TELEGRAM_CHAT_ID}"
    
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: "${EMAIL_USERNAME}"
    password: "${EMAIL_PASSWORD}"
    
  discord:
    enabled: false
    webhook_url: "${DISCORD_WEBHOOK_URL}"

# Настройки резервного копирования
backup:
  enabled: true
  interval_hours: 6
  retention_days: 30
  
  # Типы данных для бэкапа
  include:
    - database
    - configurations
    - models
    - logs
    
  # Местоположение бэкапов
  storage:
    local:
      enabled: true
      path: "backups/"
    cloud:
      enabled: false
      provider: "aws"  # aws, gcp, azure
      bucket: "${BACKUP_BUCKET}"

# Настройки разработки
development:
  debug_mode: true
  hot_reload: true
  mock_exchanges: false
  test_mode: false
  
  # Тестовые данные
  test_data:
    enabled: true
    mock_signals: true
    paper_trading: true