trading:
  risk_management:
    # Удалено - управление через risk_management.yaml
    # См. config/risk_management.yaml для настроек риска

    # Формула расчета позиции из V2:
    # position_size = (fixed_risk_balance * risk_per_trade * leverage) / entry_price
    # Пример: ($500 * 0.02 * 5) / $50000 = 0.001 BTC

  orders:
    default_leverage: 5           # 5x для production (как COPE)
    # default_leverage: 10        # 10x для development (как main)
    min_order_size: 5    # Уменьшен минимальный размер ордера (было 10)
    max_slippage: 0.002
  signals:
    process_interval: 5
    max_signal_age: 300
    min_confidence: 0.45
    min_strength: 0.2
  execution:
    order_timeout: 30
    retry_attempts: 3
    retry_delay: 2
  market_making:
    enabled: false
    spread: 0.001
    depth: 3
  paper_trading:
    enabled: false
    initial_balance: 10000
position_management:
  sync_interval: 60
  max_positions_per_symbol: 2
signal_processing:
  confidence_threshold: 0.6
  min_volume: 100000

  # Специфичные настройки для ML сигналов (из V2)
  ml_thresholds:
    buy_profit: 0.65             # Минимальная вероятность прибыли для покупки
    buy_loss: 0.35               # Максимальная вероятность убытка для покупки
    sell_profit: 0.65            # Минимальная вероятность прибыли для продажи
    sell_loss: 0.35              # Максимальная вероятность убытка для продажи
