# Конфигурация трейдеров
traders:
  # Multi-crypto трейдер для AI Signal Generator
  - id: "multi_crypto_10"
    enabled: true
    type: "multi_crypto"
    symbols:
      - "BTCUSDT"
      - "ETHUSDT"
      - "BNBUSDT"
      - "SOLUSDT"
      - "XRPUSDT"
    exchange: "bybit"
    strategy: "ml_signal"
    strategy_config:
      signal_interval: 60  # Генерация сигналов каждую минуту
      indicators:
        - type: "RSI"
          period: 14
          oversold: 30
          overbought: 70
        - type: "EMA"
          short_period: 9
          long_period: 21
    capital:
      initial: 10000
      per_trade_percentage: 2  # 2% от капитала на сделку
      max_positions: 5
    risk_management:
      stop_loss_percentage: 2
      take_profit_percentage: 5
      max_drawdown_percentage: 10
