trading:
  risk_management:
    max_position_size: 1000
    max_open_positions: 5
    max_daily_loss: 100
    risk_per_trade: 0.02
  orders:
    default_leverage: 5
    min_order_size: 10
    max_slippage: 0.002
  signals:
    process_interval: 5
    max_signal_age: 300
    min_confidence: 0.45
    min_strength: 0.2
  execution:
    order_timeout: 30
    retry_attempts: 3
    retry_delay: 2
  market_making:
    enabled: false
    spread: 0.001
    depth: 3
  paper_trading:
    enabled: false
    initial_balance: 10000
risk_management:
  enabled: true
  max_risk_per_trade: 0.02
  max_total_risk: 0.1
  max_positions: 10
  max_leverage: 10
position_management:
  sync_interval: 60
  max_positions_per_symbol: 2
signal_processing:
  confidence_threshold: 0.6
  min_volume: 100000
