"""Initial migration with base models

Revision ID: 1c2e93a85d65
Revises:
Create Date: 2025-07-30 00:29:08.282573

"""

# revision identifiers, used by Alembic.
revision = "1c2e93a85d65"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
