# Конфигурация для PatchTST ML стратегии

strategy:
  name: "PatchTST_ML_Strategy"
  type: "ml"
  class: "PatchTSTStrategy"

# Пути к моделям
models:
  model_path: "models/patchtst/model.pth"
  scaler_path: "models/patchtst/scaler.pkl"
  config_path: "models/patchtst/config.pkl"

# Параметры торговли
trading:
  # Минимальная уверенность для генерации сигнала (0-1)
  min_confidence: 0.65

  # Минимальная вероятность достижения целевого уровня прибыли
  min_profit_probability: 0.7

  # Максимальный допустимый риск (просадка/рост)
  max_risk_threshold: 0.03  # 3%

  # Режим расчета размера позиции: 'kelly' или 'fixed'
  position_sizing_mode: "kelly"

  # Коэффициент безопасности для Kelly Criterion (0-1)
  kelly_safety_factor: 0.25

  # Фиксированный процент риска (если не используется Kelly)
  fixed_risk_pct: 0.02  # 2%

  # Ограничения размера позиции
  min_position_pct: 0.01   # 1% минимум
  max_position_pct: 0.10   # 10% максимум

  # Множитель для расчета stop-loss на основе предсказанного риска
  risk_multiplier: 1.5

  # Минимальное соотношение risk/reward
  min_risk_reward_ratio: 2.0

  # Минимальная сила сигнала для торговли
  min_signal_strength: 0.6

  # Минимальный интервал между сигналами (секунды)
  min_signal_interval: 300  # 5 минут

# Веса для разных таймфреймов при голосовании
timeframe_weights:
  15m: 0.35   # Больший вес для краткосрочных
  1h: 0.30
  4h: 0.25
  12h: 0.10   # Меньший вес для долгосрочных

# Параметры для различных рыночных условий
market_conditions:
  # Высокая волатильность
  high_volatility:
    min_confidence: 0.75      # Требуем большей уверенности
    max_risk_threshold: 0.02  # Снижаем допустимый риск
    position_sizing_mode: "fixed"
    fixed_risk_pct: 0.01      # Уменьшаем размер позиции

  # Низкая волатильность
  low_volatility:
    min_confidence: 0.60
    max_risk_threshold: 0.04
    position_sizing_mode: "kelly"
    kelly_safety_factor: 0.3

  # Тренд
  trending:
    min_profit_probability: 0.65
    timeframe_weights:
      15m: 0.20
      1h: 0.30
      4h: 0.35    # Больше веса долгосрочным в тренде
      12h: 0.15

  # Флет/боковик
  ranging:
    min_profit_probability: 0.75  # Требуем большей вероятности
    timeframe_weights:
      15m: 0.40   # Больше веса краткосрочным во флете
      1h: 0.35
      4h: 0.20
      12h: 0.05

# Фильтры для сигналов
filters:
  # Временные фильтры
  time_filters:
    # Избегаем торговли в определенные часы (UTC)
    avoid_hours: []  # Например: [0, 1, 2] для избежания ночных часов

    # Избегаем торговли в выходные
    avoid_weekends: false

  # Объемные фильтры
  volume_filters:
    # Минимальный объем относительно среднего
    min_volume_ratio: 0.5

    # Период для расчета среднего объема
    volume_ma_period: 20

  # Ценовые фильтры
  price_filters:
    # Минимальное движение цены для сигнала
    min_price_change_pct: 0.001  # 0.1%

# Управление рисками
risk_management:
  # Максимальное количество одновременных позиций
  max_positions: 3

  # Максимальный риск на весь портфель
  max_portfolio_risk: 0.06  # 6%

  # Trailing stop параметры
  enable_trailing_stop: true
  trailing_stop_activation: 0.02  # Активация после 2% прибыли
  trailing_stop_distance: 0.01    # Дистанция 1%

  # Временной stop-loss (закрытие позиции по времени)
  enable_time_stop: true
  max_position_duration_hours: 48  # 2 дня максимум

# Логирование и мониторинг
monitoring:
  # Уровень логирования
  log_level: "INFO"

  # Сохранение предсказаний для анализа
  save_predictions: true
  predictions_path: "data/ml_predictions/"

  # Метрики для мониторинга
  track_metrics:
    - "prediction_accuracy"
    - "profit_probability_accuracy"
    - "risk_prediction_error"
    - "signal_quality_score"
