name: Auto Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/unit/ -v --tb=short || true

      - name: Check for secrets
        run: |
          python scripts/check_secrets.py || true

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && success()

    steps:
      - uses: actions/checkout@v4

      - name: Check if secrets are configured
        id: check_secrets
        run: |
          if [ -z "${{ secrets.STAGING_HOST }}" ]; then
            echo "::warning::STAGING_HOST secret not configured"
            echo "configured=false" >> $GITHUB_OUTPUT
          else
            echo "configured=true" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to server
        if: steps.check_secrets.outputs.configured == 'true'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          port: ${{ secrets.STAGING_PORT || 22 }}
          script: |
            cd /opt/bot_ai_v3
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            alembic upgrade head
            sudo systemctl restart bot-ai-v3
            echo "✅ Deployment complete!"

      - name: Manual deployment required
        if: steps.check_secrets.outputs.configured == 'false'
        run: |
          echo "::notice::Automatic deployment not configured. Please add GitHub Secrets:"
          echo "::notice::- STAGING_HOST (server IP)"
          echo "::notice::- STAGING_USER (SSH username)"
          echo "::notice::- STAGING_SSH_KEY (private key)"
          echo "::notice::- STAGING_PORT (optional, default 22)"
          echo "::notice::See docs/AUTOMATIC_DEPLOYMENT.md for details"
