name: Claude Code AI Review

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main, develop]

jobs:
  claude-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Claude Code Review
      uses: anthropics/claude-code-action@v1
      with:
        api-key: ${{ secrets.CLAUDE_API_KEY }}
        mode: 'review'
        review-type: 'comprehensive'
        
    - name: Security Analysis
      uses: anthropics/claude-code-action@v1
      with:
        api-key: ${{ secrets.CLAUDE_API_KEY }}
        mode: 'security'
        
    - name: Test Generation Suggestions
      uses: anthropics/claude-code-action@v1
      with:
        api-key: ${{ secrets.CLAUDE_API_KEY }}
        mode: 'test-suggestions'
        
    - name: Documentation Check
      uses: anthropics/claude-code-action@v1
      with:
        api-key: ${{ secrets.CLAUDE_API_KEY }}
        mode: 'docs'