name: Test Secrets

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check if ANTHROPIC_API_KEY is set
        run: |
          if [ -n "${{ secrets.ANTHROPIC_API_KEY }}" ]; then
            echo "✅ ANTHROPIC_API_KEY is configured"
            echo "Length: ${#SECRET_VALUE}"
          else
            echo "❌ ANTHROPIC_API_KEY is NOT configured"
            echo "Please add ANTHROPIC_API_KEY to repository secrets"
            exit 1
          fi
        env:
          SECRET_VALUE: ${{ secrets.ANTHROPIC_API_KEY }}
          
      - name: Test API Key Format
        run: |
          KEY="${{ secrets.ANTHROPIC_API_KEY }}"
          if [[ $KEY == sk-ant-* ]]; then
            echo "✅ API key format looks correct (starts with sk-ant-)"
          else
            echo "⚠️ API key format may be incorrect"
            echo "Expected format: sk-ant-api..."
          fi
          
      - name: Summary
        run: |
          echo "### Secrets Check Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Secret | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|--------|" >> $GITHUB_STEP_SUMMARY
          if [ -n "${{ secrets.ANTHROPIC_API_KEY }}" ]; then
            echo "| ANTHROPIC_API_KEY | ✅ Configured |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| ANTHROPIC_API_KEY | ❌ Missing |" >> $GITHUB_STEP_SUMMARY
          fi