name: Test Coverage Monitor

on:
  push:
    branches: [main, develop]
  pull_request:
  schedule:
    - cron: '0 */6 * * *'  # Каждые 6 часов
  workflow_dispatch:

jobs:
  monitor-coverage:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Для анализа истории
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install click pytest pytest-cov
          pip install -r requirements.txt
      
      - name: Generate test dashboard
        run: |
          python scripts/smart_test_manager.py dashboard
      
      - name: Check for missing tests
        id: check_missing
        run: |
          python scripts/smart_test_manager.py generate --update
          
          # Подсчитываем новые тесты
          NEW_TESTS=$(git status --porcelain | grep "test_.*\.py" | wc -l)
          echo "new_tests=$NEW_TESTS" >> $GITHUB_OUTPUT
      
      - name: Upload dashboard
        uses: actions/upload-artifact@v4
        with:
          name: test-dashboard
          path: tests/test_dashboard.html
      
      - name: Comment PR with coverage
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const dashboard = fs.readFileSync('tests/test_dashboard.html', 'utf8');
            
            // Извлекаем метрики из HTML
            const coverageMatch = dashboard.match(/Покрытие функций.*?(\d+\.\d+)%/);
            const coverage = coverageMatch ? coverageMatch[1] : 'N/A';
            
            const missingMatch = dashboard.match(/Отсутствует тестов.*?(\d+)/);
            const missing = missingMatch ? missingMatch[1] : 'N/A';
            
            const comment = `## 📊 Test Coverage Report
            
            - **Покрытие функций:** ${coverage}%
            - **Функций без тестов:** ${missing}
            - **Новых тестов создано:** ${{ steps.check_missing.outputs.new_tests }}
            
            [Скачать полный отчёт](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            
            ### 💡 Команды для локального запуска:
            \`\`\`bash
            # Сгенерировать недостающие тесты
            python scripts/smart_test_manager.py generate
            
            # Посмотреть дашборд
            python scripts/smart_test_manager.py dashboard
            \`\`\`
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
      
      - name: Fail if coverage too low
        run: |
          # Проверяем минимальное покрытие
          python -c "
          import json
          import sys
          
          try:
              with open('coverage.json', 'r') as f:
                  data = json.load(f)
                  coverage = data.get('totals', {}).get('percent_covered', 0)
                  
                  if coverage < 60:
                      print(f'❌ Покрытие {coverage:.1f}% ниже минимального (60%)')
                      sys.exit(1)
                  else:
                      print(f'✅ Покрытие {coverage:.1f}% в норме')
          except:
              print('⚠️ Не удалось проверить покрытие')
          "
  
  auto-fix-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: monitor-coverage
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install click pytest
          pip install -r requirements.txt
      
      - name: Auto-generate missing tests
        run: |
          python scripts/smart_test_manager.py generate
          
          # Коммитим новые тесты если есть
          if [ -n "$(git status --porcelain)" ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add tests/
            git commit -m "test: Auto-generate missing tests [skip ci]"
            git push
          fi